# Generated by Django 4.1.7 on 2023-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fav_pat',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
